Fix/removing na n for shadow
suryanshsingh2001/mockly pull request #25
Opened 2024-10-02 06:33 UTC by rahulchaudhary2244

## Pull Request Template

### **Description**
This PR addresses the issue where clearing the Blur property in the Shadow settings results in "NaN" being displayed on the UI. It is essential to handle this case appropriately to improve the user experience and ensure that "NaN" is not shown to the users.

### **Related Issue**
https://github.com/suryanshsingh2001/mockly/issues/23

Closes # (issue)
https://github.com/suryanshsingh2001/mockly/issues/23

### **Changes Made**

- Updated the ShadowManager component to validate and set default values for shadowX, shadowY, and blur properties on blur events.

### **Type of Change**

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### **Screenshots**
<img width="1435" alt="image" src="https://github.com/user-attachments/assets/2f9458d9-c342-4d66-86a5-16c0d9bf6636">

### **How Has This Been Tested?**

- _Manually tested on local environment_

### **Checklist**
_Check off the following items before submitting the pull request:_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-02 06:35 UTC, rahulchaudhary2244 commented
Hi @suryanshsingh2001 , Could you please take a look at my PR when you have some time? Also, it would be great if you could add the ```hacktoberfest-accepted``` label to ensure it gets counted for the event.

2024-10-02 18:40 UTC, suryanshsingh2001 requested changes
Hey there is one small edge case needed to handled. Border Radius cannot be less than zero.
Set the minimum value to zero for border radius.

2024-10-03 07:29 UTC, rahulchaudhary2244 commented
Hey, I reviewed the code, and it looks like this is already handled— the minimum value for the border radius is set to not go below 0.

2024-10-03 08:19 UTC, suryanshsingh2001 commented
> Hey, I reviewed the code, and it looks like this is already handled— the minimum value for the border radius is set to not go below 0.
> 
> <img alt="image" width="436" src="https://private-user-images.githubusercontent.com/54467972/373158221-6f3f5482-c777-4644-be53-f5526e3b133b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NDM1NjEsIm5iZiI6MTcyNzk0MzI2MSwicGF0aCI6Ii81NDQ2Nzk3Mi8zNzMxNTgyMjEtNmYzZjU0ODItYzc3Ny00NjQ0LWJlNTMtZjU1MjZlM2IxMzNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDA4MTQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNzczZDg0NjdjM2M2ZDEzMjkwNWEwMWQ1NGYwODZmMDJhMThjMDA1NjA5MzQxM2JhMmU4YmRiZGI3NjU5ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.k6GVkVUQZYJ0VfPaNSmCBsL9CUGgClvab7I0rGCQTyE">




https://github.com/user-attachments/assets/e3e61aed-5de3-4a96-b352-513a02dc798c

@rahulchaudhary2244 Please have a look, using the arrows still allowing negative values. But, yes otherwise it defaults to zero.

2024-10-03 08:25 UTC, rahulchaudhary2244 commented
Oh, I see now! You were referring to the ```Blur``` value—my mistake, I thought you meant ```border-radius```. You're right, this needs to be fixed. I'll take care of it.

2024-10-03 08:36 UTC, suryanshsingh2001 commented
> Oh, I see now! You were referring to the `Blur` value—my mistake, I thought you meant `border-radius`. You're right, this needs to be fixed. I'll take care of it.

My apologies for the confusion 😅!

2024-10-03 08:38 UTC, suryanshsingh2001 approved these changes
Works perfectly fine now. Good Job 👍

2024-10-03 08:42 UTC, merged

2024-10-03 08:43 UTC, rahulchaudhary2244 commented
@suryanshsingh2001 , I believe we should introduce unit tests to prevent issues like these edge cases from slipping through in the future. What do you think ?

2024-10-03 08:46 UTC, suryanshsingh2001 commented
> @suryanshsingh2001 , I believe we should introduce unit tests to prevent issues like these edge cases from slipping through in the future. What do you think ?

You are right; however, I’m not familiar with a lot of testing. Please let me know how to approach this.