Feature/custom background
suryanshsingh2001/mockly pull request #39
Opened 2024-10-17 17:24 UTC by kirito05

## Pull Request Template

### **Description**
Implemented a feature to add Custom Background Image from either from local device or pick any from web

### **Related Issue**

Closes #38 

### **Changes Made**
Created a New Function to accept the custom image and render it as the background image 
Added a custom upload button 

### **Type of Change**
_Select the type of change made with this pull request:_

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### **Screenshots (if applicable)**

https://github.com/user-attachments/assets/670d6546-8647-49fa-97e3-8dc98e3cd18f

### **How Has This Been Tested?**

- _Manually tested on local environment_

### **Checklist**
_Check off the following items before submitting the pull request:_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### **Additional Context**
_Checklist:_
- [x] Remove dotted background for custom background modal
- [x] Remove dotted background for Upload From Computer
- [x] Rename Upload From Computer button to browse files.
- [ ] For Browse files button use ghost variant of [Button](https://ui.shadcn.com/docs/components/button) component.
- [x] Make sure paste Image Link here works

_Made the changes to the UI and followed the given instructions.

2024-10-17 18:44 UTC, suryanshsingh2001 commented
Hey @kirito05, a few updates are needed:

- [ ] Remove all commits related to #35 for now as they already being revied in a separate branch.
- [ ] The Reset button isn't resetting the background.
- [ ] Clearing the link doesn't reset the background.
- [ ] Add link validation.

Additionally, there are some performance optimizations needed, which I'll cover in a detailed code review shortly.

2024-10-17 18:50 UTC, suryanshsingh2001 requested changes
These are some the changes required for this review

2024-10-17 18:50 UTC, suryanshsingh2001 commented on components/shared/Editor.tsx
> +        setIsBackgroundLoaded(true);
Are two useEffects are needed for making one functionality - setting a background.
Can we optimize this?

2024-10-17 18:50 UTC, suryanshsingh2001 commented on components/shared/Editor.tsx
> +                      <input  id="custom-background" />
This input should be shadcn Input Component, it can be found in `components/ui`

2024-10-17 18:50 UTC, suryanshsingh2001 commented on components/shared/Editor.tsx
> +                        <input type="text" className=" w-80 h-10 mt-7 mr-1 rounded-md text-center " placeholder="Paste Image Link Here" onChange={(e)=>{setCustomImg(e.target.value)}} />
This should be a shadcn input component

2024-10-18 13:13 UTC, kirito05 commented
I have made the changes for the Input component. Regarding the use of two useEffect hooks, each one is responsible for handling different image uploads, which makes the logic clearer and more modular. I attempted to combine them, but it led to overlapping logic between the custom image and the browse file functionality, resulting in incorrect behavior. In my opinion, keeping them separate improves code readability and reusability.

2024-10-18 13:18 UTC, suryanshsingh2001 commented
> I have made the changes for the Input component. Regarding the use of two useEffect hooks, each one is responsible for handling different image uploads, which makes the logic clearer and more modular. I attempted to combine them, but it led to overlapping logic between the custom image and the browse file functionality, resulting in incorrect behavior. In my opinion, keeping them separate improves code readability and reusability.

Okay, then we keep it that way.  I do not see any dip in performance as of now.

2024-10-18 13:24 UTC, suryanshsingh2001 commented
Hey @kirito05 , here some issues to resolve

https://github.com/user-attachments/assets/b9c3013e-6287-4b0b-875b-1a6989eba3f7

- [ ] Take a fresh pull from the master branch and re-apply changes.
- [ ] Remove any logic related to text wrapping.
- [ ] Add a visual cue when the user selects a custom background.
- [ ] Ensure clearing the link from the text input also clears the background.

2024-10-18 13:28 UTC, suryanshsingh2001 requested changes

2024-10-21 08:52 UTC, kirito05 commented
- [ ] Take a fresh pull from the master branch and re-apply changes.
- [x] Remove any logic related to text wrapping.
- [x] Add a visual cue when the user selects a custom background.
- [x] Ensure clearing the link from the text input also clears the background.

I have made the changes, please do check.

2024-10-21 10:29 UTC, suryanshsingh2001 approved these changes
Good

2024-10-21 10:38 UTC, suryanshsingh2001 commented
@kirito05 Looks Good, there are just two final changes required


https://github.com/user-attachments/assets/064eb478-027b-4019-9999-0d4c44bb3099




- [ ] Remove the bouncy effect on upload button and make sure the entire thing is button instead of just the icon.
- [ ] URL should be visible when I click on another tab.

2024-10-21 10:41 UTC, kirito05 commented
So you mean that when I click the back button, the image should not be reset, and the link should be visible ?? Am I correct ??

2024-10-21 10:46 UTC, suryanshsingh2001 commented
> So you mean that when I click the back button, the image should not be reset, and the link should be visible ?? Am I correct ??

@kirito05 In video, when i click on back button, background image is reset. But, if I click on any other tab, and go back,background image there but the link is not. To fix this, 

- [ ] Back button should be A Cross icon, indicating as a cancel button
- [ ] On Clicking away on any tab, image should remain and so should the url text.

2024-10-21 11:34 UTC, kirito05 commented
Made the required Changes

- [x] Back button should be Cross icon, indicating as a cancel button
- [x] On Clicking away on any tab, image should remain and so should the url text.

2024-10-21 11:45 UTC, suryanshsingh2001 commented
@kirito05 
Something is broken in the input, I think it is taking defaultValue along with current value. 
Also no need to add reset button if there is already a cross button.

These are some final changes required.

https://github.com/user-attachments/assets/51867c7b-f846-4761-9ad1-45557aa51faf

2024-10-21 12:57 UTC, suryanshsingh2001 commented
@kirito05 Awesome work, one last bug I noticed was entering a url and then go to browse files. I still see url.
What we can do is 

- [ ] When user clicks on browse files, he should see the only image name, not url input unless he cancels it.
- [ ] When user clicks on input, browse files should disappear.

Let me know if you have any other inputs for this

![image](https://github.com/user-attachments/assets/9187e35b-36bb-4ff6-94c7-440761546f6f)

2024-10-21 17:47 UTC, kirito05 commented
made the changes so that, when you enter a URL and click on the browse files then the URL won't be visible

2024-10-21 18:21 UTC, suryanshsingh2001 commented
> made the changes so that, when you enter a URL and click on the browse files then the URL won't be visible

Looks perfect now.

2024-10-21 18:21 UTC, suryanshsingh2001 approved these changes

2024-10-21 18:24 UTC, merged

2024-10-21 18:26 UTC, suryanshsingh2001 commented
Note to Self: Merge with into master branch and update the FAQ for website and README.